title: Eleanor Geniston
logo: /assets/img/headshot_circle.png
description: Quick data science & analytics project repository (Publishable only). I created this on GitHub pages.
show_downloads: false
theme: jekyll-theme-minimal
