title: Eleanor Geniston
logo: /assets/img/headshot_circle.png

description: Data Science & Analytics: Visualization & Storytelling | Automation & Delivering Business Value.
show_downloads: false
theme: jekyll-theme-minimal
