title: Hello, I'm Eleanor
logo: /assets/img/headshot_circle.png
description: This is a quick portfolio I created from the template from [here](https://jekyll.github.io/minima/about/)
show_downloads: false
theme: jekyll-theme-minimal
