title: Hello, I'm Eleanor
logo: /assets/img/headshot_circle.png
description: This is my quick portfolio and a site for some of my learning references.
show_downloads: false
theme: jekyll-theme-minimal
